### ISSUE TITLE
Add rule to prevent relying on constructor.name

### ISSUE THREAD

**Issue by nimzco** [Shopify/web-foundation#136]
I've run in two issues recently where we were relying on `constructor.name` to do things. See:
- https://github.com/Shopify/shopify/pull/145754
- https://github.com/Shopify/payment-sheet/pull/986

The problem is that since the JS is uglified, it didn't work in production while it worked in dev shops. 

We have 2 options:
  1. Setting Uglify `keep_fnames` option to `true`
  2. Write a custom linter to prevent that

I'm for option 2. What do you think people?

cc @lemonmade

**Comment by alexandcote** [comment]
Do we still want to implement this rule?

**Comment by nimzco** [comment]
Oooh that’s quite old. I left Shopify last year so I can’t really say. But you can probably close the issue I think.
Cheers!
