### ISSUE TITLE
getDerivedStateFromError() should not be flag to be a private member by the eslint rule '@shopify/react-prefer-private-members'

### ISSUE THREAD

**Issue by antoinegrant** [Shopify/web-foundation#167]
## Overview
`shopify/react-prefer-private-members` flags `getDerivedStateFromError()` to be a private member.

## Suggestion
Add `getDerivedStateFromError` to: https://github.com/Shopify/web-foundation/blob/e2499eb41da8be8388277588c9f167da0f037437/packages/eslint-plugin/lib/rules/react-prefer-private-members.js#L72

## Consuming repo
https://github.com/Shopify/checkout-web
See comment:
https://github.com/Shopify/checkout-web/pull/1775/files/53c0138727752dc96d735d1fe15fc7ce2364c0ea#r445125265

**Comment by BPScott** [comment]
Sounds good. Want to open a PR?
