### ISSUE TITLE
Decision record for not using Storybook

### ISSUE THREAD

**Issue by GoodForOneFare** [Shopify/web-foundation#60]
We've rejected baking Storybook into sewing-kit, and don't propose an alternative.  It would be great to track the exact reasons for this recommendation.

cc @lemonmade - because you have a big list of reasons, and I only remember 1 of them :|

**Comment by kaelig** [comment]
As we're on the verge of plucking content and design guidelines from polaris-react into another repository, that will leave polaris-react component docs with code examples only.

A code example is composed of: a name, a description, code snippet.

It will probably make sense to write those in a format better suited than the Markdown we have for now.

We could consider writing component examples as storybook stories, but any other alternative is equally valid.

@lemonmade your help in choosing/discarding solutions is very welcome.

**Comment by kaelig** [comment]
Update: folks @Shopify/plus-fed team are using storybook as part of https://github.com/Shopify/plus-components

**Comment by BPScott** [comment]
Yo @lemonmade: Would you be able to list your reasons why you're not a fan of Storybook? I've not used it before but a 10 second look suggests it might be handy for one of my use-cases and could fairly cleanly replace some home-grown code.

I'd be interested to hear your opinions on it to see if your concerns would affect how I'd use it?

**Comment by kaelig** [comment]
Closing this as we are re-evaluating Storybook.
