### ISSUE TITLE
Add marketing preset

### ISSUE THREAD

**Issue by mattdrose** [Shopify/web-foundation#90]
### Problem

Marketing projects use different babel presets as seen [here](https://github.com/Shopify/marketing_assets/blob/master/config/marketing-assets-preset.js). Right now, this needs to be copied to different marketing projects.

### Proposal

Add marketing specific configuration to `babel-preset-shopify`.

### Syntax

```
{
  "babel": {
    "presets": ["shopify/marketing"]
  }
}
```

or

```
{
  "babel": {
    "presets": [
      ["shopify/web", {"type": "marketing"}]
    ]
  }
}
```

**Comment by alexandcote** [comment]
👋🏼 Hi @mattdrose, is it still an issue?
